Special_Orders/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("orders.urls")),
    path("vendors/", include("vendors.urls")),
    path("customers/", include("customers.urls")),
    path("select2/", include("django_select2.urls")),
]

customers/urls.py
from django.urls import path, include

from .views import (
    CustomerListCreateView,
    CustomerUpdateView,
    CustomerDeleteView,
    filter_customers,
    display_cards,
    display_list,
)
import orders.views

app_name = "customers"

filter_and_display_paths = [
    path("filter/", filter_customers, name="filter-orders"),
    path("display_cards/", display_cards, name="display-cards"),
    path("display_list/", display_list, name="display-list"),
]

urlpatterns = [
    path("",
        include(
            [
                path("", CustomerListCreateView.as_view(), name="list-customers"),
                *filter_and_display_paths,
            ]
        ),
    ),
    path("<int:pk>/edit_customer/",
        include(
            [
                path("", CustomerUpdateView.as_view(), name="edit-customer"),
                *filter_and_display_paths,
            ]
        ),
    ),
    path(
        "<int:pk>/delete_customer/",
        CustomerDeleteView.as_view(),
        name="delete-customer",
    ),
    path(
        "<int:customer_id>/orders/",
        include(
            [
                path("", orders.views.CustomerOrderListView.as_view(), name="customer-orders"),
                path("filter/", orders.views.filter_orders, name="customer-filter-orders"),
                path("display_cards/", orders.views.display_cards, name="order-display-cards"),
                path("display_list/", orders.views.display_list, name="order-display-list"),
            ]
        ),
    ),
]

orders/urls.py
from django.urls import path, include

from . import views

app_name = "orders"

filter_and_display_paths = [
    path("filter/", views.filter_orders, name="filter-orders"),
    path("display_cards/", views.display_cards, name="display-cards"),
    path("display_list/", views.display_list, name="display-list"),
]

urlpatterns = [
    path("",
        include(
            [
                path("", views.OrderListCreateView.as_view(), name="home"),
                *filter_and_display_paths,
            ]
        ),
    ),
    path("<int:pk>/edit_order/",
        include(
            [
                path("", views.OrderUpdateView.as_view(), name="edit-order"),
                *filter_and_display_paths,
            ]
         ),
    ),
    path(
        "<int:pk>/copy_order/",
        include(
            [
                path("", views.OrderListCreateView.as_view(), name="copy-order"),
                *filter_and_display_paths,
            ]
        ),
    ),
    path(
        "orders/<status>/",
        include (
            [
                path("", views.OrderListCreateView.as_view(), name="filtered-orders"),
                *filter_and_display_paths,
            ]
        ),
    ),
    path("<int:pk>/delete_order/", views.send_order_to_trash, name="delete-order"),
    path("<int:pk>/restore_order/", views.restore_order, name="restore-order"),
    path(
        "order_update_status/<int:order_id>/<action>/",
        views.order_update_status,
        name="order-update-status",
    ),
    path(
        "<int:pk>/force_delete_order/",
        views.force_delete_order,
        name="force-delete-order",
    ),
    path(
        "<int:pk>/unpaid_pickup/",
        views.unpaid_pickup,
        name="unpaid-pickup",
    ),
]

vendors/urls.py
from django.urls import path

from . import views

app_name = "vendors"
urlpatterns = [
    path("", views.VendorListCreateView.as_view(), name="list-vendors"),
    path("<int:pk>/edit_vendor", views.VendorUpdateView.as_view(), name="edit-vendor"),
    path(
        "<int:pk>/delete_vendor", views.VendorDeleteView.as_view(), name="delete-vendor"
    ),
]

orders/models.py
from django.db import models
from django.core.validators import MinValueValidator

from datetime import date, timedelta
from decimal import *

from customers.models import Customer
from vendors.models import Vendor


class Order(models.Model):
    INCOMPLETE = "INCOMPLETE"
    READY_TO_ORDER = "READY_TO_ORDER"
    ORDERED = "ORDERED"
    RECEIVED = "RECEIVED"
    CALLED = "CALLED"
    PICKED_UP = "PICKED_UP"
    DELETED = "DELETED"

    ORDER_STATUS = [
        (INCOMPLETE, "Incomplete"),
        (READY_TO_ORDER, "Ready to order"),
        (ORDERED, "Ordered"),
        (RECEIVED, "Received"),
        (CALLED, "Called"),
        (PICKED_UP, "Picked-Up"),
        (DELETED, "Deleted"),
    ]

    description = models.CharField(max_length=128)
    vendor = models.ForeignKey(Vendor, on_delete=models.PROTECT, blank=True, null=True)
    product_number = models.CharField(max_length=64, blank=True, null=True)

    quantity = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(1)], blank=True, null=True
    )
    book_price = models.DecimalField(
        decimal_places=2,
        max_digits=6,
        validators=[MinValueValidator(0.0)],
        blank=True,
        null=True,
    )
    has_bottle_deposit = models.BooleanField(default=False)
    number_bottle_deposit = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(1)], blank=True, null=True
    )

    customer = models.ForeignKey(
        Customer, on_delete=models.PROTECT, blank=True, null=True
    )
    paid = models.BooleanField(default=False)
    is_suspended = models.BooleanField(default=False)

    status = models.CharField(choices=ORDER_STATUS, max_length=64, null=True)
    is_stand_by = models.BooleanField(default=False)
    is_cancelled = models.BooleanField(default=False)
    memo = models.TextField(max_length=500, null=True, blank=True)
    employee_initials = models.CharField(max_length=5)

    date_created = models.DateTimeField(auto_now_add=True)
    date_ordered = models.DateField(null=True, blank=True)
    date_received = models.DateField(null=True, blank=True)
    date_called = models.DateField(null=True, blank=True)
    date_picked_up = models.DateField(null=True, blank=True)

    date_deleted = models.DateField(null=True, blank=True)

    def is_complete(self):
        """
        Check if all required fields are filled.
        Returns True if all required fields are filled, False otherwise.
        """
        return all(
            [
                self.vendor is not None,
                self.product_number is not None,
                self.quantity is not None,
                self.book_price is not None,
                not self.has_bottle_deposit or self.number_bottle_deposit is not None,
                self.customer is not None,
                self.total_price() is not None,
            ]
        )

    def previous_status(self):
        """
        Go back to the previous status.
        """
        match self.status:
            case self.INCOMPLETE:
                self.send_to_trash()
            case self.READY_TO_ORDER:
                self.send_to_trash()
            case self.ORDERED:
                self.date_ordered = None
            case self.RECEIVED:
                self.date_received = None
            case self.CALLED:
                self.date_called = None
            case self.PICKED_UP:
                self.date_picked_up = None
        self.update_status()

    def next_status(self):
        """
        Go to the next status by adding a date to the order field.
        """
        match self.status:
            case self.INCOMPLETE:
                pass
            case self.READY_TO_ORDER:
                self.date_ordered = date.today()
            case self.ORDERED:
                self.date_received = date.today()
            case self.RECEIVED:
                self.date_called = date.today()
            case self.CALLED:
                self.date_picked_up = date.today()
        self.update_status()

    def update_status(self):
        """
        Update the status of the order based on the dates and the status.
        """
        # Order is deleted
        if self.date_deleted is not None:
            self.status = self.DELETED
            self.save()
            return

        # Revive a deleted item with temporary status
        if self.status == self.DELETED and self.date_deleted is None:
            self.status = self.INCOMPLETE
        # Make sure all orders have a status
        if self.status is None:
            self.status = self.INCOMPLETE

        # Order is incomplete
        if not self.is_complete():
            self.status = self.INCOMPLETE
            self.save()
            return

        # Order has a date-related status
        if self.date_picked_up is not None:
            self.status = self.PICKED_UP
        elif self.date_called is not None:
            self.status = self.CALLED
        elif self.date_received is not None:
            self.status = self.RECEIVED
        elif self.date_ordered is not None:
            self.status = self.ORDERED
        # Order is complete and does not have a date-related status
        elif self.is_complete():
            self.status = self.READY_TO_ORDER

        self.save()

    def unsuspend_paid_order(self):
        if self.paid:
            self.is_suspended = False
        self.save()

    def send_to_trash(self):
        self.date_deleted = date.today()
        self.update_status()

    def restore(self):
        self.date_deleted = None
        self.update_status()

    def permanently_delete(self):
        """
        Permanently delete an order after 30 days
        """
        if self.date_deleted and (
            date.today() - self.date_deleted > timedelta(days=30)
        ):
            self.delete()

    def total_price(self):
        """
        Calculate the total price of the order based on the customer's margin.
        """
        try:
            return Decimal(
                self.customer.add_margin(self.book_price * self.quantity)
            ).quantize(Decimal("0.01"))
        except TypeError:
            return None
        except AttributeError:
            return None

vendors/models.py
from django.db import models


class Vendor(models.Model):
    DAYS_OF_WEEK = (
        ("0", "Monday"),
        ("1", "Tuesday"),
        ("2", "Wednesday"),
        ("3", "Thursday"),
        ("4", "Friday"),
        ("5", "Saturday"),
        ("6", "Sunday"),
    )

    name = models.CharField(max_length=128)
    ordering_method = models.CharField(max_length=64, blank=True, null=True)
    order_day = models.CharField(
        max_length=1, choices=DAYS_OF_WEEK, blank=True, null=True
    )
    delivery_day = models.CharField(
        max_length=1, choices=DAYS_OF_WEEK, blank=True, null=True
    )
    rank = models.PositiveSmallIntegerField(blank=False, null=False, default="99")

    class Meta:
        ordering = ["rank", "name"]

    def __str__(self):
        return self.name

vendors/forms.py
from django import forms

from . import models


class VendorForm(forms.ModelForm):
    class Meta:
        model = models.Vendor
        fields = [
            "name",
            "ordering_method",
            "order_day",
            "delivery_day",
            "rank",
        ]

vendors/views.py
from django.shortcuts import reverse, redirect
from django.views import generic

from .models import Vendor
from .forms import VendorForm


class VendorListCreateView(generic.CreateView):
    model = Vendor
    form_class = VendorForm
    template_name = "vendors/vendor_home.html"

    def get_success_url(self):
        return reverse("vendors:list-vendors")

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the vendors
        context["vendor_list"] = Vendor.objects.all()
        return context


class VendorUpdateView(generic.UpdateView):
    model = Vendor
    form_class = VendorForm
    template_name = "vendors/vendor_home.html"

    def get_success_url(self):
        return reverse("vendors:list-vendors")

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the vendors
        context["vendor_list"] = Vendor.objects.all()
        context["action"] = "update"
        return context

    def post(self, request, *args, **kwargs):
        if "cancel" in request.POST:
            url = self.get_success_url()
            return redirect(url)
        else:
            return super(VendorUpdateView, self).post(request, *args, **kwargs)


class VendorDeleteView(generic.DeleteView):
    model = Vendor

    def get_success_url(self):
        return reverse("vendors:list-vendors")

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the vendors
        context["vendor_list"] = Vendor.objects.all()
        return context

vendors/templates/vendors/partials/add_vendor.html
<div class="col-4">
    <form class="form vendor-form" method="post">
        {% csrf_token %}
        <div class="card border-primary bg-ticket mt-2 mb-1">
            <div id="btn-add-vendor" class="card-header bg-primary text-white pb-2 col-auto" type="button"
                 data-bs-toggle="collapse"
                 data-bs-target=".collapse-add-vendor"
                 aria-expanded="false" aria-controls="collapseExample" onclick="this.blur();">
                <div class="row ">
                    <span class="col">Add a new vendor</span>

                    <i id="fa-btn-add-vendor" class="fa-solid fa-circle-plus col-auto my-auto"></i>
                </div>
            </div>
            <div class="card-body collapse collapse-add-vendor py-0">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item px-0 pb-1">
                        {% include 'vendors/partials/vendor_form_fields.html' with save_button=True %}
                    </li>
                </ul>
            </div>
        </div>
    </form>
</div>

vendors/templates/vendors/partials/delete_vendor.html
<!-- Trigger/Open the Modal -->
<button class="btn-orders ms-1" type="button"
        data-bs-toggle="modal" data-bs-target="#delete-vendor-{{ vendor.id }}">
    <i class="fa-solid fa-trash"></i></button>

<!-- The Modal -->
<div class="modal fade"
     id="delete-vendor-{{ vendor.id }}" data-bs-backdrop="static" data-bs-keyboard="false"
     tabindex="-1" aria-labelledby="staticBackdrop{{ vendor.id }}" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdrop{{ vendor.id }}">Delete Vendor</h5>
                <button type="button" class="close btn-orders" data-bs-dismiss="modal" aria-label="Close">
                    <span class="p-2" aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body text-center">
                {% if vendor.order_set.count == 0 %}
                <p>Are you sure you want to delete the vendor {{ vendor.name }}?</p>
                {% elif vendor.order_set.count == 1 %}
                <p>You are not allowed to delete this vendor, as an order is using it.</p>
                {% elif vendor.order_set.count > 1 %}
                <p>You are not allowed to delete this vendor, as {{ vendor.order_set.count }} orders are using it.</p>
                {% endif %}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                {% if vendor.order_set.count == 0 %}
                <form action="{% url 'vendors:delete-vendor' vendor.id %}" method="post">
                    {% csrf_token %}
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
                {% endif %}
            </div>
        </div>
    </div>
</div>

vendors/templates/vendors/partials/list_vendors.html
{% for vendor in vendor_list %}
<div class="col-auto px-1">
    {% include 'vendors/partials/vendor_snippet.html' %}
</div>
{% endfor %}

vendors/templates/vendors/partials/update_vendor.html
<div class="col-4">
    <form class="form vendor-form" method="post">
        {% csrf_token %}
        <div class="card border-warning bg-ticket mt-2 mb-1">
            <div class="card-header bg-warning pb-2">
                <div class="row ">
                    <span class="col-auto">Edit vendor</span>
                </div>
            </div>
            <div class="card-body py-0">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item px-0 pb-1">
                        {% include 'vendors/partials/vendor_form_fields.html' with save_button=True %}
                    </li>
                </ul>
            </div>
        </div>

    </form>
</div>

vendors/templates/vendors/partials/vendor_filter.html
{% load bootstrap5 %}

<div class="col">
    <form class="filter vendor-filter row my-2" method="get">
        <div class="col">
            {% bootstrap_field filter.form.name show_label=False size="small" layout="horizontal"
            form_group_class="mb-1 pe-0" field_class=" pe-0" label_class="" %}
        </div>
        <div class="col-auto mb-1 me-0 justify-content-end">
            <div class="row mb-1 mx-0 justify-content-end gap-2">
                <a class="col btn btn-dark btn-sm" href="#" onclick="location.reload()">Clear filters</a>
            </div>
            <input class="align-self-end btn btn-primary btn-sm" type="submit" value="Apply filters"/>
        </div>
    </form>
</div>

vendors/templates/vendors/partials/vendor_form_fields.html
{% load bootstrap5 %}


<div class="row mb-1">
    {% bootstrap_field form.name show_label=False size="small"
    form_group_class="col row" field_class="col customer-form-field" %}
    {% bootstrap_field form.rank show_label=False size="small"
    form_group_class="vendor-rank row" field_class="col customer-form-field" %}
</div>
<div class="row mb-1">
    {% bootstrap_field form.ordering_method size="small" layout="horizontal"
    field_class="col-auto" label_class="col-auto" placeholder="phone #, email..."
    form_group_class="row" %}
</div>
<div class="row">
    {% bootstrap_field form.order_day size="small" layout="horizontal"
    form_group_class="col-auto mb-1" field_class="col-auto px-0" label_class="col-auto" %}
    {% bootstrap_field form.delivery_day size="small" layout="horizontal"
    form_group_class="mb-1 col-auto" field_class="col-auto px-0" label_class="col-auto" %}

    {% if save_button %}
    <div class="gap-1 d-flex justify-content-end">
        {% if action == 'update' %}
        <button class="btn btn-warning btn-sm mb-1" type="submit" name="cancel" value="cancel">Cancel</button>
        {% bootstrap_button "Save" button_type="submit" button_class="btn-primary btn-sm mb-1"
        size="sm" %}
        {% else %}
        {% bootstrap_button "Add" button_type="submit" button_class="btn-primary btn-sm mb-1"
        size="sm" extra_classes="col-auto" %}
        {% endif %}
    </div>
    {% endif %}

</div>

vendors/templates/vendors/partials/vendor_snippet.html
<div class="card border-primary bg-ticket my-1">
    <div class="card-header">
        <div class="row ">
            <span class="col-auto">
                <span class="col-auto me-auto">{{ vendor.name }}</span>
            </span>
            <span class="col-auto ms-auto ">
                <span class="col-auto">
                    <span class="badge rounded-pill bg-secondary">
                        {% if vendor.rank > 99 %}
                            <i class="fa-solid fa-infinity"></i>
                        {% else %}
                            {{ vendor.rank }}
                        {% endif %}
                    </span>
                    <a class="btn-orders" href="{% url 'vendors:edit-vendor' vendor.id %}">
                        <i class="fa-solid fa-pen"></i></a>
                    {% include 'vendors/partials/delete_vendor.html' %}
                </span>
            </span>
        </div>

    </div>
    <div class="card-body">
        <ul class="list-group list-group-flush">
            <li class="list-group-item px-0 d-grid gap-2">
                <div>Order method: {{ vendor.ordering_method }}</div>
                <div>Order by: {{ vendor.get_order_day_display }}</div>
                <div>Delivery on: {{ vendor.get_delivery_day_display }}</div>
            </li>
        </ul>
    </div>
</div>