Special_Orders/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("orders.urls")),
    path("vendors/", include("vendors.urls")),
    path("customers/", include("customers.urls")),
    path("select2/", include("django_select2.urls")),
]

orders/urls.py
from django.urls import path, include

from . import views

app_name = "orders"

filter_and_display_paths = [
    path("filter/", views.filter_orders, name="filter-orders"),
    path("display_cards/", views.display_cards, name="display-cards"),
    path("display_list/", views.display_list, name="display-list"),
]

urlpatterns = [
    path("",
        include(
            [
                path("", views.OrderListCreateView.as_view(), name="home"),
                *filter_and_display_paths,
            ]
        ),
    ),
    path("<int:pk>/edit_order/",
        include(
            [
                path("", views.OrderUpdateView.as_view(), name="edit-order"),
                *filter_and_display_paths,
            ]
         ),
    ),
    path(
        "<int:pk>/copy_order/",
        include(
            [
                path("", views.OrderListCreateView.as_view(), name="copy-order"),
                *filter_and_display_paths,
            ]
        ),
    ),
    path(
        "orders/<status>/",
        include (
            [
                path("", views.OrderListCreateView.as_view(), name="filtered-orders"),
                *filter_and_display_paths,
            ]
        ),
    ),
    path("<int:pk>/delete_order/", views.send_order_to_trash, name="delete-order"),
    path("<int:pk>/restore_order/", views.restore_order, name="restore-order"),
    path(
        "order_update_status/<int:order_id>/<action>/",
        views.order_update_status,
        name="order-update-status",
    ),
    path(
        "<int:pk>/force_delete_order/",
        views.force_delete_order,
        name="force-delete-order",
    ),
    path(
        "<int:pk>/unpaid_pickup/",
        views.unpaid_pickup,
        name="unpaid-pickup",
    ),
]

orders/forms.py
from django import forms
from django.shortcuts import get_object_or_404
from django_select2 import forms as s2forms
from bootstrap_datepicker_plus.widgets import DatePickerInput

from .models import Order, Vendor
from customers.models import Customer, CustomerStatus

from customers.forms import CustomerForm


class CustomerWidget(s2forms.ModelSelect2Widget):
    search_fields = [
        "first_name__icontains",
        "last_name__icontains",
        "phone_number__icontains",
        "email__icontains",
    ]

    def build_attrs(self, base_attrs, extra_attrs=None):
        attrs = super().build_attrs(base_attrs, extra_attrs)
        attrs["data-minimum-input-length"] = 0
        attrs["data-placeholder"] = "Search a customer by their name or phone number"
        return attrs

    def get_queryset(self):
        return Customer.objects.order_by("last_name", "first_name")


class VendorWidget(s2forms.ModelSelect2Widget):
    search_fields = [
        "name__icontains",
    ]

    def build_attrs(self, base_attrs, extra_attrs=None):
        attrs = super().build_attrs(base_attrs, extra_attrs)
        attrs["data-minimum-input-length"] = 0
        attrs["data-placeholder"] = "Search a vendor by their name"
        return attrs


class CreateOrderForm(forms.ModelForm):
    new_customer_form = CustomerForm()
    create_new_customer = forms.BooleanField(
        required=False, label="Create a new customer", initial="false"
    )

    class Meta:
        model = Order
        fields = [
            "description",
            "vendor",
            "product_number",
            "quantity",
            "book_price",
            "paid",
            "is_suspended",
            "has_bottle_deposit",
            "number_bottle_deposit",
            "memo",
            "employee_initials",
            "customer",
            "create_new_customer",
            "is_stand_by",
            "is_cancelled",
            "date_ordered",
            "date_received",
            "date_called",
            "date_picked_up",
        ]

        date_picker_options = {
            "format": "MM/DD/YYYY",
            "extraFormats": ["MM/DD/YY"],
            "showClose": True,
            "showClear": True,
            "showTodayButton": True,
            "widgetPositioning": {
                "vertical": "bottom",
            },
        }

        widgets = {
            "customer": CustomerWidget,
            "vendor": VendorWidget,
            "date_ordered": DatePickerInput(options=date_picker_options),
            "date_received": DatePickerInput(options=date_picker_options),
            "date_called": DatePickerInput(options=date_picker_options),
            "date_picked_up": DatePickerInput(options=date_picker_options),
        }

        labels = {
            "product_number": "Product #",
            "has_bottle_deposit": "Bottle Deposit",
            "is_suspended": "Suspended",
            "is_stand_by": "Stand By",
            "is_cancelled": "Cancelled",
            "date_picked_up": "Date picked-up",
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Set the custom label for the Vendor field
        self.fields["vendor"].empty_label = "Vendor"

    def clean(self):
        cleaned_data = super().clean()

        if self.data.get("create_new_customer") == "true":
            # Create a new customer
            new_customer_data = {
                "first_name": self.data.get("first_name"),
                "last_name": self.data.get("last_name"),
                "company": self.data.get("company"),
                "phone_number": self.data.get("phone_number"),
                "email": self.data.get("email"),
            }
            if any(new_customer_data.values()):
                if self.data.get("status"):
                    new_customer_data["status"] = get_object_or_404(
                        CustomerStatus, id=self.data.get("status")
                    )
                new_customer = Customer.objects.create(**new_customer_data)
                cleaned_data["customer"] = new_customer

        return cleaned_data

orders/views.py
from django.shortcuts import redirect, reverse, get_object_or_404
from django.contrib import messages
from django.core.paginator import Paginator
from django.template.loader import render_to_string
from django.views import generic
from django.http import JsonResponse
from django.db.models.functions import Lower

from django_filters.views import FilterView

from .models import Order
from .forms import CreateOrderForm
from .filters import OrderFilter, CustomerOrderFilter

from preferences.models import Preference


class OrderFilterView(FilterView):
    model = Order
    filterset_class = OrderFilter
    template_name = "orders/order_base.html"
    context_object_name = "filter"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["origin"] = "order"
        context["display_choice"] = Preference.objects.get(user__username__iexact="abundance").order_view
        return context


class OrderListCreateView(generic.CreateView, OrderFilterView):
    form_class = CreateOrderForm

    def get_initial(self):
        if "pk" in self.kwargs:
            original_order = get_object_or_404(Order, id=self.kwargs["pk"])
            initial = {
                "description": original_order.description,
                "vendor": original_order.vendor,
                "product_number": original_order.product_number,
                "quantity": original_order.quantity,
                "has_bottle_deposit": original_order.has_bottle_deposit,
                "number_bottle_deposit": original_order.number_bottle_deposit,
                "memo": original_order.memo,
                "customer": original_order.customer,
            }
            return initial
        return {}

    def get_success_url(self):
        return reverse("orders:home")

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        context["action"] = "create"
        if self.get_initial and "pk" in self.kwargs:
            context["action"] = "copy"
        return context

    def form_valid(self, form):
        order = form.save(commit=False)
        order.update_status()
        order.unsuspend_paid_order()
        return super().form_valid(form)


class OrderUpdateView(generic.UpdateView, OrderFilterView):
    form_class = CreateOrderForm

    def get_success_url(self):
        return reverse("orders:home")

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        context["action"] = "update"
        context["order"] = self.get_object()
        return context

    def form_valid(self, form):
        order = form.save(commit=False)
        if "delete" in self.request.POST:
            order.send_to_trash()
            messages.success(
                self.request,
                f"The order has been successfully sent to trash. It will be definitely deleted in 30 days.",
            )
            return redirect("orders:home")
        if "restore" in self.request.POST:
            order.restore()
            messages.success(
                self.request,
                f"The order has been successfully restored.",
            )
            return redirect("orders:home")
        order.update_status()
        order.unsuspend_paid_order()
        return super().form_valid(form)


class CustomerOrderListView(OrderListCreateView):
    filterset_class = CustomerOrderFilter

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        context["origin"] = "customer-order"
        return context


def filter_orders(request, **kwargs):
    # Get the filters from the request
    order_filters = request.GET

    if "customer_id" in kwargs:
        # Show all orders by customer
        customer_id = kwargs["customer_id"]
        order_filter = CustomerOrderFilter(
            order_filters, queryset=Order.objects.filter(customer=customer_id)
        )
    elif "status" in kwargs:
        # Show all orders by status
        status = kwargs["status"]
        order_filter = OrderFilter(
            order_filters, queryset=Order.objects.filter(status__iexact=status)
        )
    else:
        # Show all orders except the deleted ones
        order_filter = OrderFilter(
            order_filters, queryset=Order.objects.exclude(status=Order.DELETED)
        )

    # Get the filtered queryset
    filtered_orders = order_filter.qs

    # Set default ordering
    default_ordering = request.GET.get("ordering", None)
    if not default_ordering:
        # Default ordering if none is provided in the request
        filtered_orders = filtered_orders.order_by(
            "-date_created", Lower("vendor__name")
        )

    paginator = Paginator(filtered_orders, 20)
    page_number = request.GET.get("page")
    page_orders = paginator.get_page(page_number)

    preference = Preference.objects.get(user__username__iexact="abundance")

    # Render items to a string
    orders_html = render_to_string(
        "orders/partials/order_list.html",
        {"order_list": page_orders,
         "display": preference.order_view},
        request=request,
    )
    # Convert the list to JSON and return it as a response
    return JsonResponse({"item_list_html": orders_html})


def order_update_status(request, order_id, action):
    if request.method == "PUT":
        # Retrieve instance and update status
        order = get_object_or_404(Order, id=order_id)
        if action == "previous_step" and order.status not in [
            Order.INCOMPLETE,
            Order.READY_TO_ORDER,
        ]:
            order.previous_status()
        elif action == "next_step":
            if order.status == Order.INCOMPLETE:
                redirect_data = {
                    "redirect": reverse("orders:edit-order", kwargs={"pk": order.id}),
                }
                return JsonResponse(redirect_data)
            order.next_status()
        order.save()

        # Define template for the order snippet
        template = "orders/partials/order_table_snippet.html"
        preference = Preference.objects.get(user__username__iexact="abundance")
        if preference.order_view == Preference.CARDS:
            template = "orders/partials/order_card_snippet.html"

        # Render order to a string
        order_html = render_to_string(
            template,
            {"order": order},
            request=request,
        )
        return JsonResponse({"order": order_html})


def send_order_to_trash(request, pk):
    order = get_object_or_404(Order, id=pk)
    if request.method == "POST":
        order.send_to_trash()
        messages.success(
            request,
            f"The order has been successfully sent to trash. It will be permanently deleted in 30 days.",
        )
        return redirect("orders:home")
    return redirect("orders:home")


def restore_order(request, pk):
    order = get_object_or_404(Order, id=pk)
    if request.method == "POST":
        order.restore()
        messages.success(
            request,
            f"The order has been successfully restored.",
        )
        return redirect("orders:filtered-orders", status="deleted")
    return redirect("orders:home")


def force_delete_order(request, pk):
    order = get_object_or_404(Order, id=pk)
    if request.method == "POST":
        order.delete()
        messages.success(
            request,
            f"The order {order.description} has been successfully deleted.",
        )
    return redirect("orders:filtered-orders", status="deleted")


def unpaid_pickup(request, pk):
    order = get_object_or_404(Order, id=pk)
    if request.method == "POST":
        if "paid" in request.POST:
            order.paid = True
        order.next_status()
        order.save()
    return redirect("orders:home")


def display_cards(request, **kwargs):
    if request.method == "POST":
        preference = Preference.objects.get(user__username__iexact="abundance")
        preference.order_view = Preference.CARDS
        preference.save()
    return JsonResponse({"status": "success"})


def display_list(request, **kwargs):
    if request.method == "POST":
        preference = Preference.objects.get(user__username__iexact="abundance")
        preference.order_view = Preference.LIST
        preference.save()
    return JsonResponse({"status": "success"})

orders/templates/orders/partials/modals/delete_modal.html
<!-- Delete Modal -->
<div class="modal fade"
     id="delete-order-{{ order.id }}" data-bs-backdrop="static" data-bs-keyboard="false"
     tabindex="-1" aria-labelledby="staticBackdrop{{ order.id }}" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdrop{{ order.id }}">Delete Order</h5>
                <button type="button" class="close btn-orders" data-bs-dismiss="modal" aria-label="Close">
                    <span class="p-2" aria-hidden="true"><i class="fa-regular fa-circle-xmark"></i></span>
                </button>
            </div>
            <div class="modal-body text-center">
                <p>Are you sure you want to delete the order of {{ order.description }}?</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <form action="{% url 'orders:delete-order' order.id %}"
                      method="post">
                    {% csrf_token %}
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
            </div>
        </div>
    </div>
</div>

orders/templates/orders/partials/modals/force_delete_modal.html
<!-- Force Delete Modal -->
<div class="modal fade"
     id="force-delete-order-{{ order.id }}" data-bs-backdrop="static" data-bs-keyboard="false"
     tabindex="-1" aria-labelledby="staticBackdrop{{ order.id }}" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdrop{{ order.id }}">Permanently Delete Order</h5>
                <button type="button" class="close btn-orders" data-bs-dismiss="modal" aria-label="Close">
                    <span class="p-2" aria-hidden="true"><i class="fa-regular fa-circle-xmark"></i></span>
                </button>
            </div>
            <div class="modal-body text-center">
                <p>Are you sure you want to permanently delete the order of {{ order.description }}?</p>
                <p>It will be lost forever. <i class="fa-solid fa-skull"></i></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <form action="{% url 'orders:force-delete-order' order.id %}"
                      method="post">
                    {% csrf_token %}
                    <input class="btn btn-danger" type="submit" value="Delete Forever">
                </form>
            </div>
        </div>
    </div>
</div>

orders/templates/orders/partials/modals/modal_conditions.html
{% load orders_extras %}

{% if order.status|previous_step == 'Delete' %}
{% include 'orders/partials/modals/delete_modal.html' %}
{% endif %}

{% if order.status|next_step == 'Picked-Up' and not order.paid %}
{% include 'orders/partials/modals/pickup_modal.html' %}
{% endif %}

orders/templates/orders/partials/modals/pickup_modal.html
<!-- Pickup Modal -->
<div class="modal fade"
     id="pickup-order-{{ order.id }}" data-bs-backdrop="static" data-bs-keyboard="false"
     tabindex="-1" aria-labelledby="staticBackdrop{{ order.id }}" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdrop{{ order.id }}">Pick-Up Order</h5>
                <button type="button" class="close btn-orders" data-bs-dismiss="modal" aria-label="Close">
                    <span class="p-2" aria-hidden="true"><i class="fa-regular fa-circle-xmark"></i></span>
                </button>
            </div>
            <div class="modal-body text-center">
                <p>This order has not yet been paid.</p>
                <p>Are you sure you want to mark it as picked-up?</p>
            </div>
            <div class="modal-footer justify-content-center">
                <form action="{% url 'orders:unpaid-pickup' order.id %}" method="post">
                    {% csrf_token %}
                    <button type="button" class="btn btn-secondary btn-sm" data-bs-dismiss="modal">Cancel</button>
                    <input type="hidden" value="{{ request.get_full_path }}" name="url">
                    <input class="btn btn-success btn-sm" type="submit" name="paid" value="It has been paid!">
                    <input class="btn btn-warning btn-sm" type="submit" name="not_paid" value="Not paid ¯\_(ツ)_/¯">
                </form>
            </div>
        </div>
    </div>
</div>