Special_Orders/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("orders.urls")),
    path("vendors/", include("vendors.urls")),
    path("customers/", include("customers.urls")),
    path("select2/", include("django_select2.urls")),
]

customers/urls.py
from django.urls import path, include

from .views import (
    CustomerListCreateView,
    CustomerUpdateView,
    CustomerDeleteView,
    filter_customers,
    display_cards,
    display_list,
)
import orders.views

app_name = "customers"

filter_and_display_paths = [
    path("filter/", filter_customers, name="filter-orders"),
    path("display_cards/", display_cards, name="display-cards"),
    path("display_list/", display_list, name="display-list"),
]

urlpatterns = [
    path("",
        include(
            [
                path("", CustomerListCreateView.as_view(), name="list-customers"),
                *filter_and_display_paths,
            ]
        ),
    ),
    path("<int:pk>/edit_customer/",
        include(
            [
                path("", CustomerUpdateView.as_view(), name="edit-customer"),
                *filter_and_display_paths,
            ]
        ),
    ),
    path(
        "<int:pk>/delete_customer/",
        CustomerDeleteView.as_view(),
        name="delete-customer",
    ),
    path(
        "<int:customer_id>/orders/",
        include(
            [
                path("", orders.views.CustomerOrderListView.as_view(), name="customer-orders"),
                path("filter/", orders.views.filter_orders, name="customer-filter-orders"),
                path("display_cards/", orders.views.display_cards, name="order-display-cards"),
                path("display_list/", orders.views.display_list, name="order-display-list"),
            ]
        ),
    ),
]

orders/urls.py
from django.urls import path, include

from . import views

app_name = "orders"

filter_and_display_paths = [
    path("filter/", views.filter_orders, name="filter-orders"),
    path("display_cards/", views.display_cards, name="display-cards"),
    path("display_list/", views.display_list, name="display-list"),
]

urlpatterns = [
    path("",
        include(
            [
                path("", views.OrderListCreateView.as_view(), name="home"),
                *filter_and_display_paths,
            ]
        ),
    ),
    path("<int:pk>/edit_order/",
        include(
            [
                path("", views.OrderUpdateView.as_view(), name="edit-order"),
                *filter_and_display_paths,
            ]
         ),
    ),
    path(
        "<int:pk>/copy_order/",
        include(
            [
                path("", views.OrderListCreateView.as_view(), name="copy-order"),
                *filter_and_display_paths,
            ]
        ),
    ),
    path(
        "orders/<status>/",
        include (
            [
                path("", views.OrderListCreateView.as_view(), name="filtered-orders"),
                *filter_and_display_paths,
            ]
        ),
    ),
    path("<int:pk>/delete_order/", views.send_order_to_trash, name="delete-order"),
    path("<int:pk>/restore_order/", views.restore_order, name="restore-order"),
    path(
        "order_update_status/<int:order_id>/<action>/",
        views.order_update_status,
        name="order-update-status",
    ),
    path(
        "<int:pk>/force_delete_order/",
        views.force_delete_order,
        name="force-delete-order",
    ),
    path(
        "<int:pk>/unpaid_pickup/",
        views.unpaid_pickup,
        name="unpaid-pickup",
    ),
]

customers/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator

from decimal import *


class CustomerStatus(models.Model):
    class Meta:
        verbose_name_plural = "customer statuses"

    NON_SHAREHOLDER = "NON_SHAREHOLDER"
    SHAREHOLDER = "SHAREHOLDER"
    SHAREHOLDER_RESALE = "SHAREHOLDER_RESALE"
    EMPLOYEE = "EMPLOYEE"
    FLOWER = "FLOWER"

    STATUS_CHOICES = [
        (NON_SHAREHOLDER, "Non-shareholder"),
        (SHAREHOLDER, "Shareholder"),
        (SHAREHOLDER_RESALE, "Shareholder Resale"),
        (EMPLOYEE, "Employee"),
        (FLOWER, "FLOWER (Non-Redeemable Share)"),
    ]
    status = models.CharField(choices=STATUS_CHOICES, max_length=64, unique=True)
    margin = models.DecimalField(
        decimal_places=2,
        max_digits=6,
        validators=[MinValueValidator(0.0), MaxValueValidator(100.0)],
    )

    def __str__(self):
        return f"{dict(self.STATUS_CHOICES)[str(self.status)]}"


class Customer(models.Model):
    first_name = models.CharField(max_length=128, null=True, blank=True)
    last_name = models.CharField(max_length=128, null=True, blank=True)
    company = models.CharField(max_length=128, null=True, blank=True)
    phone_number = models.CharField(max_length=128, null=True, blank=True)
    status = models.ForeignKey(
        CustomerStatus, on_delete=models.PROTECT, null=True, blank=True
    )
    email = models.EmailField(max_length=128, null=True, blank=True)

    def save(self, *args, **kwargs):
        if self.phone_number:
            self.phone_number = "".join(filter(str.isdigit, self.phone_number))
        super(Customer, self).save(*args, **kwargs)

    def __str__(self):
        status = ""
        if self.status and self.status.status == CustomerStatus.FLOWER:
            status = ", FLOWER Member"
        return f"{self.last_name}, {self.first_name}, {self.phone_number_formatted()}{status}"

    def add_margin(self, book_price):
        return book_price / (Decimal(100) - self.status.margin) * 100

    def phone_number_formatted(self):
        if self.phone_number:
            if len(self.phone_number) == 10:
                return f"({self.phone_number[:3]}) {self.phone_number[3:6]}-{self.phone_number[6:]}"
            if len(self.phone_number) == 7:
                return f"(585) {self.phone_number[:3]}-{self.phone_number[3:]}"
            if len(self.phone_number) > 10:
                return f"({self.phone_number[:3]}) {self.phone_number[3:6]}-{self.phone_number[6:10]} ext {self.phone_number[10:]}"
            return self.phone_number
        return None

orders/models.py
from django.db import models
from django.core.validators import MinValueValidator

from datetime import date, timedelta
from decimal import *

from customers.models import Customer
from vendors.models import Vendor


class Order(models.Model):
    INCOMPLETE = "INCOMPLETE"
    READY_TO_ORDER = "READY_TO_ORDER"
    ORDERED = "ORDERED"
    RECEIVED = "RECEIVED"
    CALLED = "CALLED"
    PICKED_UP = "PICKED_UP"
    DELETED = "DELETED"

    ORDER_STATUS = [
        (INCOMPLETE, "Incomplete"),
        (READY_TO_ORDER, "Ready to order"),
        (ORDERED, "Ordered"),
        (RECEIVED, "Received"),
        (CALLED, "Called"),
        (PICKED_UP, "Picked-Up"),
        (DELETED, "Deleted"),
    ]

    description = models.CharField(max_length=128)
    vendor = models.ForeignKey(Vendor, on_delete=models.PROTECT, blank=True, null=True)
    product_number = models.CharField(max_length=64, blank=True, null=True)

    quantity = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(1)], blank=True, null=True
    )
    book_price = models.DecimalField(
        decimal_places=2,
        max_digits=6,
        validators=[MinValueValidator(0.0)],
        blank=True,
        null=True,
    )
    has_bottle_deposit = models.BooleanField(default=False)
    number_bottle_deposit = models.PositiveSmallIntegerField(
        validators=[MinValueValidator(1)], blank=True, null=True
    )

    customer = models.ForeignKey(
        Customer, on_delete=models.PROTECT, blank=True, null=True
    )
    paid = models.BooleanField(default=False)
    is_suspended = models.BooleanField(default=False)

    status = models.CharField(choices=ORDER_STATUS, max_length=64, null=True)
    is_stand_by = models.BooleanField(default=False)
    is_cancelled = models.BooleanField(default=False)
    memo = models.TextField(max_length=500, null=True, blank=True)
    employee_initials = models.CharField(max_length=5)

    date_created = models.DateTimeField(auto_now_add=True)
    date_ordered = models.DateField(null=True, blank=True)
    date_received = models.DateField(null=True, blank=True)
    date_called = models.DateField(null=True, blank=True)
    date_picked_up = models.DateField(null=True, blank=True)

    date_deleted = models.DateField(null=True, blank=True)

    def is_complete(self):
        """
        Check if all required fields are filled.
        Returns True if all required fields are filled, False otherwise.
        """
        return all(
            [
                self.vendor is not None,
                self.product_number is not None,
                self.quantity is not None,
                self.book_price is not None,
                not self.has_bottle_deposit or self.number_bottle_deposit is not None,
                self.customer is not None,
                self.total_price() is not None,
            ]
        )

    def previous_status(self):
        """
        Go back to the previous status.
        """
        match self.status:
            case self.INCOMPLETE:
                self.send_to_trash()
            case self.READY_TO_ORDER:
                self.send_to_trash()
            case self.ORDERED:
                self.date_ordered = None
            case self.RECEIVED:
                self.date_received = None
            case self.CALLED:
                self.date_called = None
            case self.PICKED_UP:
                self.date_picked_up = None
        self.update_status()

    def next_status(self):
        """
        Go to the next status by adding a date to the order field.
        """
        match self.status:
            case self.INCOMPLETE:
                pass
            case self.READY_TO_ORDER:
                self.date_ordered = date.today()
            case self.ORDERED:
                self.date_received = date.today()
            case self.RECEIVED:
                self.date_called = date.today()
            case self.CALLED:
                self.date_picked_up = date.today()
        self.update_status()

    def update_status(self):
        """
        Update the status of the order based on the dates and the status.
        """
        # Order is deleted
        if self.date_deleted is not None:
            self.status = self.DELETED
            self.save()
            return

        # Revive a deleted item with temporary status
        if self.status == self.DELETED and self.date_deleted is None:
            self.status = self.INCOMPLETE
        # Make sure all orders have a status
        if self.status is None:
            self.status = self.INCOMPLETE

        # Order is incomplete
        if not self.is_complete():
            self.status = self.INCOMPLETE
            self.save()
            return

        # Order has a date-related status
        if self.date_picked_up is not None:
            self.status = self.PICKED_UP
        elif self.date_called is not None:
            self.status = self.CALLED
        elif self.date_received is not None:
            self.status = self.RECEIVED
        elif self.date_ordered is not None:
            self.status = self.ORDERED
        # Order is complete and does not have a date-related status
        elif self.is_complete():
            self.status = self.READY_TO_ORDER

        self.save()

    def unsuspend_paid_order(self):
        if self.paid:
            self.is_suspended = False
        self.save()

    def send_to_trash(self):
        self.date_deleted = date.today()
        self.update_status()

    def restore(self):
        self.date_deleted = None
        self.update_status()

    def permanently_delete(self):
        """
        Permanently delete an order after 30 days
        """
        if self.date_deleted and (
            date.today() - self.date_deleted > timedelta(days=30)
        ):
            self.delete()

    def total_price(self):
        """
        Calculate the total price of the order based on the customer's margin.
        """
        try:
            return Decimal(
                self.customer.add_margin(self.book_price * self.quantity)
            ).quantize(Decimal("0.01"))
        except TypeError:
            return None
        except AttributeError:
            return None

customers/forms.py
from django import forms

from . import models


class CustomerForm(forms.ModelForm):
    class Meta:
        model = models.Customer
        fields = [
            "first_name",
            "last_name",
            "company",
            "phone_number",
            "email",
            "status",
        ]
        labels = {
            "phone_number": "Phone #",
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Set the custom label for the ForeignKey field
        self.fields["status"].empty_label = "Status"

customers/views.py
from django.shortcuts import reverse, redirect, render
from django.core.paginator import Paginator
from django.template.loader import render_to_string
from django.views import generic
from django.http import JsonResponse
from django.db.models.functions import Lower
from django.urls import reverse_lazy

from django_filters.views import FilterView

from .models import Customer
from .forms import CustomerForm
from .filters import CustomerFilter

from preferences.models import Preference


class CustomerFilterView(FilterView):
    model = Customer
    filterset_class = CustomerFilter
    template_name = "customers/customer_base.html"
    context_object_name = "filter"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["origin"] = "customer"
        context["display_choice"] = Preference.objects.get(user__username__iexact="abundance").customer_view
        return context


class CustomerListCreateView(generic.CreateView, CustomerFilterView):
    form_class = CustomerForm

    def get_initial(self):
        if "pk" in self.kwargs:
            original_customer = get_object_or_404(Customer, id=self.kwargs["pk"])
            initial = {
                "first_name": original_customer.first_name,
                "last_name": original_customer.last_name,
                "email": original_customer.email,
                "phone": original_customer.phone,
                "status": original_customer.status,
                "memo": original_customer.memo,
            }
            return initial
        return {}

    def get_success_url(self):
        return reverse("customers:list-customers")

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        context["action"] = "create"
        if self.get_initial and "pk" in self.kwargs:
            context["action"] = "copy"
        return context


class CustomerUpdateView(generic.UpdateView, CustomerFilterView):
    form_class = CustomerForm

    def get_success_url(self):
        return reverse("customers:list-customers")

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        context["action"] = "update"
        context["customer"] = self.get_object()
        return context

    def form_valid(self, form):
        customer = form.save(commit=False)
        if "delete" in self.request.POST:
            customer.delete()
            return redirect("customers:list-customers")
        return super().form_valid(form)


class CustomerDeleteView(CustomerFilterView, generic.DeleteView):
    model = Customer
    success_url = reverse_lazy("customers:list-customers")


def filter_customers(request, **kwargs):
    # Get the filters from the request
    customer_filters = request.GET

    if "status" in kwargs:
        # Show all customers by status
        status = kwargs["status"]
        customer_filter = CustomerFilter(
            customer_filters, queryset=Customer.objects.filter(status__iexact=status)
        )
    else:
        # Show all customers
        customer_filter = CustomerFilter(customer_filters, queryset=Customer.objects.all())

    # Get the filtered queryset
    filtered_customers = customer_filter.qs

    # Set default ordering
    default_ordering = request.GET.get("ordering", None)
    if not default_ordering:
        # Default ordering if none is provided in the request
        filtered_customers = filtered_customers.order_by(
            Lower("last_name")
        )

    paginator = Paginator(filtered_customers, 20)
    page_number = request.GET.get("page")
    page_customers = paginator.get_page(page_number)
    # Render items to a string
    customers_html = render_to_string(
        "customers/partials/list_customers.html",
        {"customer_list": page_customers,
         "display": Preference.objects.get(user__username__iexact="abundance").customer_view},
        request=request,
    )
    # Convert the list to JSON and return it as a response
    return JsonResponse({"item_list_html": customers_html})

def display_cards(request, **kwargs):
    if request.method == "POST":
        preference = Preference.objects.get(user__username__iexact="abundance")
        preference.customer_view = Preference.CARDS
        preference.save()
    return JsonResponse({"status": "success"})


def display_list(request, **kwargs):
    if request.method == "POST":
        preference = Preference.objects.get(user__username__iexact="abundance")
        preference.customer_view = Preference.LIST
        preference.save()
    return JsonResponse({"status": "success"})

customers/templates/customers/partials/add_customer.html
<div class="col-4">
    <form class="form customer-form" method="post">
        {% csrf_token %}
        <div class="card border-primary bg-ticket my-2">
            <div id="btn-add-customer" class="card-header bg-primary text-white pb-2 col-auto" type="button"
                 data-bs-toggle="collapse"
                 data-bs-target=".collapse-add-customer"
                 aria-expanded="false" aria-controls="collapseExample" onclick="this.blur();">
                <div class="row ">
                    <span class="col">Add a new customer</span>

                    <i id="fa-btn-add-customer" class="fa-solid fa-circle-plus col-auto my-auto"></i>
                </div>
            </div>
            <div class="card-body collapse collapse-add-customer py-0">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item px-0 pb-1">
                        {% include 'customers/partials/customer_form_fields.html' with save_button=True %}
                    </li>
                </ul>
            </div>
        </div>
    </form>
</div>

customers/templates/customers/partials/customer_card.html
<div class="row">
    {% for customer in customer_list %}

    <div class="col-auto">
        <div class="card border-primary bg-ticket my-2">
            <div class="card-header">
                <div class="row ">
            <span class="col-auto">
                <span class="col-auto me-auto">{{ customer.last_name }}, {{ customer.first_name}}</span>
            </span>
                    <span class="col-auto ms-auto ">
                <span class="col-auto">
                    <a class="btn-orders px-1" type="button" data-bs-toggle="tooltip" data-bs-placement="bottom"
                       title="Show customer's orders"
                       href="{% url 'customers:customer-orders' customer.id %}">
                        <i class="fa-solid fa-cart-shopping"></i>
                    </a>
                    <a class="btn-orders px-1" href="{% url 'customers:edit-customer' customer.id %}">
                            <i class="fa-solid fa-pen"></i></a>
                        {% include 'customers/partials/delete_customer.html' %}
                </span>
            </span>
                </div>

            </div>
            <div class="card-body">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item px-0 d-grid gap-2">
                        <div>Company: {{ customer.company }}</div>
                        <div>Phone Number: {{ customer.phone_number }}</div>
                        <div>Email: {{ customer.email }}</div>
                        <div>Status: {{ customer.status }}</div>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    {% endfor %}
</div>

customers/templates/customers/partials/customer_form_fields.html
{% load bootstrap5 %}


<div class="row mb-1">
    {% bootstrap_field form.first_name show_label=False size="small"
    form_group_class="col row" field_class="col customer-form-field" %}
    {% bootstrap_field form.last_name show_label=False size="small"
    form_group_class="col row" field_class="col customer-form-field" %}
</div>
<div class="row mb-1">
    {% bootstrap_field form.phone_number show_label=False size="small"
    form_group_class="col row" field_class="col customer-form-field" %}
    {% bootstrap_field form.email show_label=False size="small"
    form_group_class="col row" field_class="col customer-form-field" %}
</div>
<div class="row mb-1">
    {% bootstrap_field form.status show_label=False
    size="small" form_group_class="col row" field_class="col customer-form-field" %}
    {% bootstrap_field form.company show_label=False size="small"
    form_group_class="col row" field_class="col customer-form-field" %}

    {% if save_button %}
    <div class="col-auto">
        {% if action == 'update' %}
        <button class="btn btn-warning btn-sm mb-1" type="submit" name="cancel" value="cancel">Cancel</button>
        {% bootstrap_button "Save" button_type="submit" button_class="btn-primary btn-sm mb-1"
        size="sm" %}
        {% else %}
        {% bootstrap_button "Add" button_type="submit" button_class="btn-primary btn-sm mb-1"
        size="sm" extra_classes="col-auto" %}
        {% endif %}
    </div>
    {% endif %}

</div>

customers/templates/customers/partials/customer_list.html
<table class="table table-striped border-primary mt-2">
    <thead>
    <tr>
        <th scope="col">Last Name</th>
        <th scope="col">First Name</th>
        <th scope="col">Company</th>
        <th scope="col">Phone Number</th>
        <th scope="col">Email</th>
        <th scope="col">Shareholder Status</th>
        <th scope="col"></th>
        <th scope="col"></th>
    </tr>
    </thead>
    <tbody>

    {% for customer in customer_list %}

    <tr>
        <td>{{ customer.last_name|default_if_none:"" }}</td>
        <td>{{ customer.first_name|default_if_none:"" }}</td>
        <td>{{ customer.company|default_if_none:"" }}</td>
        <td>{{ customer.phone_number_formatted|default_if_none:"" }}</td>
        <td>{{ customer.email|default_if_none:"" }}</td>
        <td>{{ customer.status|default_if_none:"" }}</td>
        <td>
            <a class="btn-orders px-1" type="button" data-bs-toggle="tooltip" data-bs-placement="bottom"
               title="Show customer's orders"
               href="{% url 'customers:customer-orders' customer.id %}">
                <i class="fa-solid fa-cart-shopping"></i>
            </a>
        </td>
        <td>
            <a class="btn-orders px-1"
               href="{% url 'customers:edit-customer' customer.id %}?customer_full_info={{ request.GET.customer_full_info }}&status={{ request.GET.status }}">
                <i class="fa-solid fa-pen"></i>
            </a>
        </td>
        <td>
            {% include 'customers/partials/delete_customer.html' %}
        </td>
    </tr>

    {% endfor %}

    </tbody>
</table>

customers/templates/customers/partials/customer_table.html
<table class="table table-striped border-primary mt-2">
    <thead>
    <tr>
        <th scope="col">Last Name</th>
        <th scope="col">First Name</th>
        <th scope="col">Company</th>
        <th scope="col">Phone Number</th>
        <th scope="col">Email</th>
        <th scope="col">Shareholder Status</th>
        <th scope="col"></th>
        <th scope="col"></th>
    </tr>
    </thead>
    <tbody>

    {% for customer in customer_list %}

    <tr>
        <td>{{ customer.last_name|default_if_none:"" }}</td>
        <td>{{ customer.first_name|default_if_none:"" }}</td>
        <td>{{ customer.company|default_if_none:"" }}</td>
        <td>{{ customer.phone_number_formatted|default_if_none:"" }}</td>
        <td>{{ customer.email|default_if_none:"" }}</td>
        <td>{{ customer.status|default_if_none:"" }}</td>
        <td>
            <a type="button" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Show customer's orders"
               href="{% url 'customers:customer-orders' customer.id %}">
                <i class="fa-solid fa-cart-shopping"></i>
            </a>
        </td>
        <td>
            <a class="btn-orders"
               href="{% url 'customers:edit-customer' customer.id %}?customer_full_info={{ request.GET.customer_full_info }}&status={{ request.GET.status }}">
                <i class="fa-solid fa-pen"></i>
            </a>
        </td>
        <td>
            {% include 'customers/partials/delete_customer.html' %}
        </td>
    </tr>

    {% endfor %}

    </tbody>
</table>

customers/templates/customers/partials/delete_customer.html
<!-- Trigger/Open the Modal -->
<button class="btn-orders ms-1" type="button" data-bs-toggle="modal"
        data-bs-target="#delete-customer-{{ customer.id }}">
    <i class="fa-solid fa-trash"></i>
</button>

<!-- The Modal -->
<div class="modal fade"
     id="delete-customer-{{ customer.id }}" data-bs-backdrop="static" data-bs-keyboard="false"
     tabindex="-1" aria-labelledby="staticBackdrop{{ customer.id }}" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdrop{{ customer.id }}">Delete Customer</h5>
                <button type="button" class="close btn-orders" data-bs-dismiss="modal" aria-label="Close">
                    <span class="p-2" aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body text-center">
                {% if customer.order_set.count == 0 %}
                <p>Are you sure you want to delete the customer {{ customer.name }}?</p>
                {% elif customer.order_set.count == 1 %}
                <p>You are not allowed to delete this customer, because this customer has one order saved.</p>
                {% elif customer.order_set.count > 1 %}
                <p>You are not allowed to delete this customer, because this customer has {{ customer.order_set.count }}
                    orders saved.</p>
                {% endif %}
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                {% if customer.order_set.count == 0 %}
                <form action="{% url 'customers:delete-customer' customer.id %}?customer_full_info={{ request.GET.customer_full_info }}&status={{ request.GET.status }}"
                      method="post">
                    {% csrf_token %}
                    <input class="btn btn-danger" type="submit" value="Delete">
                </form>
                {% endif %}
            </div>
        </div>
    </div>
</div>

customers/templates/customers/partials/list_customers.html
{% if display == 'CARDS' %}

{% include 'customers/partials/customer_card.html' %}

{% else %}

{% include 'customers/partials/customer_list.html' %}

{% endif %}

{% include "partials/pagination.html" with page=customer_list %}

customers/templates/customers/partials/update_customer.html
<div class="col-4">
    <form class="form customer-form" method="post">
        {% csrf_token %}
        <div class="card border-warning bg-ticket my-2">
            <div class="card-header bg-warning pb-2">
                <div class="row ">
                    <span class="col-auto">Edit customer</span>
                </div>
            </div>
            <div class="card-body py-0">
                <ul class="list-group list-group-flush">
                    <li class="list-group-item px-0 pb-1">
                        {% include 'customers/partials/customer_form_fields.html' with save_button=True %}
                    </li>
                </ul>
            </div>
        </div>

    </form>
</div>