Special_Orders/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("orders.urls")),
    path("vendors/", include("vendors.urls")),
    path("customers/", include("customers.urls")),
    path("select2/", include("django_select2.urls")),
]

customers/urls.py
from django.urls import path, include

from .views import (
    CustomerListCreateView,
    CustomerUpdateView,
    CustomerDeleteView,
    filter_customers,
    display_cards,
    display_list,
)
import orders.views

app_name = "customers"

filter_and_display_paths = [
    path("filter/", filter_customers, name="filter-orders"),
    path("display_cards/", display_cards, name="display-cards"),
    path("display_list/", display_list, name="display-list"),
]

urlpatterns = [
    path("",
        include(
            [
                path("", CustomerListCreateView.as_view(), name="list-customers"),
                *filter_and_display_paths,
            ]
        ),
    ),
    path("<int:pk>/edit_customer/",
        include(
            [
                path("", CustomerUpdateView.as_view(), name="edit-customer"),
                *filter_and_display_paths,
            ]
        ),
    ),
    path(
        "<int:pk>/delete_customer/",
        CustomerDeleteView.as_view(),
        name="delete-customer",
    ),
    path(
        "<int:customer_id>/orders/",
        include(
            [
                path("", orders.views.CustomerOrderListView.as_view(), name="customer-orders"),
                path("filter/", orders.views.filter_orders, name="customer-filter-orders"),
                path("display_cards/", orders.views.display_cards, name="order-display-cards"),
                path("display_list/", orders.views.display_list, name="order-display-list"),
            ]
        ),
    ),
]

orders/urls.py
from django.urls import path, include

from . import views

app_name = "orders"

filter_and_display_paths = [
    path("filter/", views.filter_orders, name="filter-orders"),
    path("display_cards/", views.display_cards, name="display-cards"),
    path("display_list/", views.display_list, name="display-list"),
]

urlpatterns = [
    path("",
        include(
            [
                path("", views.OrderListCreateView.as_view(), name="home"),
                *filter_and_display_paths,
            ]
        ),
    ),
    path("<int:pk>/edit_order/",
        include(
            [
                path("", views.OrderUpdateView.as_view(), name="edit-order"),
                *filter_and_display_paths,
            ]
         ),
    ),
    path(
        "<int:pk>/copy_order/",
        include(
            [
                path("", views.OrderListCreateView.as_view(), name="copy-order"),
                *filter_and_display_paths,
            ]
        ),
    ),
    path(
        "orders/<status>/",
        include (
            [
                path("", views.OrderListCreateView.as_view(), name="filtered-orders"),
                *filter_and_display_paths,
            ]
        ),
    ),
    path("<int:pk>/delete_order/", views.send_order_to_trash, name="delete-order"),
    path("<int:pk>/restore_order/", views.restore_order, name="restore-order"),
    path(
        "order_update_status/<int:order_id>/<action>/",
        views.order_update_status,
        name="order-update-status",
    ),
    path(
        "<int:pk>/force_delete_order/",
        views.force_delete_order,
        name="force-delete-order",
    ),
    path(
        "<int:pk>/unpaid_pickup/",
        views.unpaid_pickup,
        name="unpaid-pickup",
    ),
]

vendors/urls.py
from django.urls import path

from . import views

app_name = "vendors"
urlpatterns = [
    path("", views.VendorListCreateView.as_view(), name="list-vendors"),
    path("<int:pk>/edit_vendor", views.VendorUpdateView.as_view(), name="edit-vendor"),
    path(
        "<int:pk>/delete_vendor", views.VendorDeleteView.as_view(), name="delete-vendor"
    ),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
{{ form.media.css }}
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}

<html lang="en" class="h-100">
<head>
    <meta charset="UTF-8">
    <title>Special Order - Abundance Food Co-op</title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'media/favicon_io/apple-touch-icon.png' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'media/favicon_io/favicon.ico' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'media/favicon_io/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'media/favicon_io/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'media/favicon_io/site.webmanifest' %}">

</head>
<body class="h-100">

<div class="cover-container d-flex w-100 h-100 mx-auto flex-column">
    <nav class="container-fluid navbar sticky-top navbar-expand-md navbar-light bg-light py-0 no-print">
        <a class="navbar-brand" href="{% url 'orders:home' %}">
            <img src="{% static 'media/Abundance_Logo.png' %}" width="200" class="d-inline-block align-middle me-2"
                 alt="">
            Special Orders
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item"><a class="nav-link" href="{% url 'orders:home' %}">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'orders:filtered-orders' status='deleted' %}">
                    Deleted Orders</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'customers:list-customers' %}">Customers</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'vendors:list-vendors' %}">Vendors</a></li>
            </ul>
        </div>
    </nav>
    <div>
        <div>
            {# Display django.contrib.messages as Bootstrap alerts #}
            {% bootstrap_messages %}
        </div>
    </div>
    <main role="main" class="inner cover">
        <div class="container">
            {% block content %}{% endblock %}
        </div>
    </main>
    <footer class="mt-auto no-print">
        <div class="text-center bg-light py-2 px-0 mt-4">
        <span>
            Developed by
            <a href="https://github.com/franfif/"
               target="_blank" rel="noopener noreferrer">Francis Barrow</a>
            - <a href="https://abundance.coop/"
                 target="_blank" rel="noopener noreferrer">Abundance Food Co-op</a> 2024
        </span>
        </div>
    </footer>
</div>
{% csrf_token %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="{% static 'bundle.js' %}"></script>

{{ form.media.js }}

</body>
</html>